### ISSUE TITLE
error  in running  "Train.."

### ISSUE THREAD

**Issue by bkomaki** [MRV1N2/3D_Printing_Error_Detection_with_AI#1]
when I run the Train "train.py": I've got this error below:
Traceback (most recent call last):
  File "C:\3d\3D_Printing_Error_Detection_with_AI-main\3D_Printing_Error_Detection_with_AI-main\train.py", line 74, in <module>
    Ai_handler()
  File "C:\3d\3D_Printing_Error_Detection_with_AI-main\3D_Printing_Error_Detection_with_AI-main\ai_handler.py", line 37, in __init__
    self._study = optuna.create_study(direction="minimize",
  File "C:\Users\Administrator\anaconda3\lib\site-packages\optuna\_convert_positional_args.py", line 63, in converter_wrapper
    return func(**kwargs)
  File "C:\Users\Administrator\anaconda3\lib\site-packages\optuna\study\study.py", line 1156, in create_study
    storage = storages.get_storage(storage)
  File "C:\Users\Administrator\anaconda3\lib\site-packages\optuna\storages\__init__.py", line 43, in get_storage
    return _CachedStorage(RDBStorage(storage))
  File "C:\Users\Administrator\anaconda3\lib\site-packages\optuna\storages\_rdb\storage.py", line 231, in __init__
    self._version_manager.check_table_schema_compatibility()
  File "C:\Users\Administrator\anaconda3\lib\site-packages\optuna\storages\_rdb\storage.py", line 1137, in check_table_schema_compatibility
    raise RuntimeError(message)
RuntimeError: The runtime optuna version 3.1.0 is no longer compatible with the table schema (set up by optuna 2.10.0). Please execute `$ optuna storage upgrade --storage $STORAGE_URL` for upgrading the storage.
>>>

**Comment by lnknf** [comment]
This error occurs, because the [ai_3d_printing_error_detection.db](https://github.com/MRV1N2/3D_Printing_Error_Detection_with_AI/blob/main/ai_3d_printing_error_detection.db) file was created with optuna 2.10.0, but you have version 3.1.0 installed. You can either just delete the file and optuna will create a new one, or you downgrade your optuna version to 2.10.0, which I wouldn't recommend tho. Or, you can run the command recommended by the error to upgrade the file to the newer version.
